// Hvigor wrapper script
// This file is auto-generated by Hvigor and should not be modified.
// It handles the download and execution of the Hvigor build tool.

const path = require('path');
const fs = require('fs');

const HVIGOR_VERSION = '5.0.6';
const HVIGOR_APP_HOME = path.resolve(__dirname, '..');

function getHvigorWrapperPath() {
  return path.join(HVIGOR_APP_HOME, 'oh_modules', '@ohos', 'hvigor', 'bin', 'hvigor.js');
}

function main() {
  const hvigorPath = getHvigorWrapperPath();
  if (fs.existsSync(hvigorPath)) {
    require(hvigorPath);
  } else {
    console.error('Hvigor not found. Please run npm install first.');
    process.exit(1);
  }
}

main();
